"use client";
import { useRef, useState } from "react";

type Tab = "DOCUMENT" | "CANVAS" | "PUBLISH";
const tabs: Tab[] = ["DOCUMENT", "CANVAS", "PUBLISH"];

function Panel({ tab }: { tab: Tab }) {
  if (tab === "CANVAS") return <div className="fig-sheet canvas-sheet"><div className="sheet-head"><h4>SPATIAL FIELD</h4><span>CANVAS / 02</span></div><div className="sheet-body canvas-body"><svg className="can-links" viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true"><path d="M25 25 C45 20 50 42 69 25" pathLength="1" /><path d="M25 25 C22 55 52 68 42 78" pathLength="1" /><path d="M69 25 C65 55 52 68 42 78" pathLength="1" /></svg><div className="mini-card star" style={{ "--t": "16%", "--l": "10%", "--r": "-3deg" } as React.CSSProperties}><b>BUILD LOG</b><span>note / 01</span></div><div className="mini-card" style={{ "--t": "16%", "--l": "61%", "--r": "2deg" } as React.CSSProperties}><b>READING QUEUE</b><span>note / 02</span></div><div className="mini-card" style={{ "--t": "66%", "--l": "32%", "--r": "-2deg" } as React.CSSProperties}><b>LAUNCH PLAN</b><span>note / 03</span></div></div><div className="sheet-foot"><span>⌘ Z / 50 STATES</span><span>72% ZOOM · 3 NOTES</span></div></div>;
  if (tab === "PUBLISH") return <div className="fig-sheet"><div className="sheet-head"><h4>PUBLIC SPECIMEN</h4><span>SOON / 03</span></div><div className="sheet-body publish-sheet"><p className="publish-url">jam-note.app/pub/you/build-log</p><h3>Build log — s4/w38</h3><p>Shipped the canvas undo stack this week. Fifty entries deep, snapshotted once per gesture.</p><span className="publish-tag">PUBLISHED WITH JAM NOTES</span></div><div className="sheet-foot"><span>PUBLIC URL</span><span>SELF-PUBLISHING / SOON</span></div></div>;
  return <div className="fig-sheet"><div className="sheet-head"><h4>BUILD LOG — S4/W38</h4><span>DOCUMENT / 01</span></div><div className="sheet-body"><ul className="outline"><li>wire the autosave debounce <i className="chk">✓</i></li><li>cut the canvas beta over to production</li><li>ship the paste parser <i className="qm">—</i></li><li>notes that nest forever<ul><li>one note, many surfaces</li><li>keyboard-first by default</li></ul></li></ul></div><div className="sheet-foot"><span>BLOCK EDITOR · READY</span><span>⌘K / SEARCH</span></div></div>;
}

export function FeatureShowcase() {
  const [active, setActive] = useState<Tab>("DOCUMENT"); const tabRefs = useRef<(HTMLButtonElement | null)[]>([]);
  const selectByKey = (event: React.KeyboardEvent) => { const index = tabs.indexOf(active); let next = -1; if (event.key === "ArrowRight") next = (index + 1) % tabs.length; if (event.key === "ArrowLeft") next = (index - 1 + tabs.length) % tabs.length; if (event.key === "Home") next = 0; if (event.key === "End") next = tabs.length - 1; if (next < 0) return; event.preventDefault(); setActive(tabs[next]); tabRefs.current[next]?.focus(); };
  return <section className="spread modes" id="modes"><span className="folio-n">02</span><div className="wrap"><div className="section-head" data-reveal data-drift><p className="kicker">SPREAD 02 — MODES</p><h2 className="h-xl">ONE NOTE,<br /><span className="circ">THREE</span> WAYS</h2><p className="dek">Every note is a document and a spatial board at the same time — the same blocks, the same save, two geometries.</p></div><div className="modes-grid" data-reveal><div className="modes-copy"><p className="note-m">THE SAME THOUGHT / THREE SURFACES</p><p className="dek">Write linearly, arrange spatially, then publish the draft when it is ready. No export step, no duplicate source.</p></div><div className="figure"><div className="fig-tabs" role="tablist" aria-label="Note modes" onKeyDown={selectByKey}>{tabs.map((tab, i) => <button key={tab} ref={(node) => { tabRefs.current[i] = node; }} id={`tab-${tab.toLowerCase()}`} className={`fig-tab ${active === tab ? "is-active" : ""}`} role="tab" aria-selected={active === tab} aria-controls="mode-panel" tabIndex={active === tab ? 0 : -1} onClick={() => setActive(tab)}>{tab}{tab === "PUBLISH" && <i>SOON</i>}</button>)}</div><div className="fig-stage" id="mode-panel" key={active} role="tabpanel" aria-labelledby={`tab-${active.toLowerCase()}`} tabIndex={0}><Panel tab={active} /></div><div className="fig-read"><span>◉ {active} VIEW</span><span>ONE NOTE / MANY GEOMETRIES</span></div></div></div></div></section>;
}
